Repository ariyanstechies/Hairways, pull requests merged in 2019-08, with the labels that each got.

#130 share like and number of views working
  home/admin.py
  home/models.py
  home/static/css/main.css
  home/static/js/moreinfo.js
  home/templates/home/index.html
  home/templates/home/show.html
  home/urls.py
  home/views.py
Labels: ready for review

#133 share button now working
  home/owners.py
  home/static/css/main.css
  home/templates/home/show.html
Labels: bug, ready for review

#139 added slug url for salons \n renamed Salons table to Salon
  home/admin.py
  home/migrations/0006_salons_url.py
  home/migrations/0007_auto_20190802_2308.py
  home/models.py
  home/owners.py
  home/templates/home/index.html
  home/urls.py
  home/views.py
Labels: feature :ok_hand:, ready for review

#138 signup issue fixed
  home/clients.py
  home/models.py
  home/templates/clients/client_comments.html
Labels: bug, ready for review

#146 comment form now working
  home/forms.py
  home/migrations/0008_auto_20190803_1147.py
  home/models.py
  home/static/css/main.css
  home/templates/home/show.html
  home/templates/shared/footer.html
  home/urls.py
  home/views.py
Labels: ready for review

#147 Created map and fixed map and carousel
  base/settings.py
  home/static/css/main.css
  home/templates/home/show.html
  home/views.py
Labels: feature :ok_hand:

#151 fixed urls NoReverseMatch error
  home/owners.py
  home/urls.py
  home/views.py
Labels: bug, ready for review

#152 enabled profile picture upload during registration to clients
  .gitignore
  base/settings.py
  home/admin.py
  home/forms.py
  home/models.py
  home/templates/clients/mini_dashboard.html
  home/templates/home/index.html
  home/templates/registration/signup_form.html
  home/views.py
Labels: feature :ok_hand:

#153 Beautify index
  home/static/css/main.css
  home/templates/home/index.html
  home/templates/shared/footer.html
  home/templates/shared/navbar.html
Labels: feature :ok_hand:, ready for review
