Repository ariyanstechies/Hairways, pull requests merged in 2019-07, with the labels that each got.

#115 List Comments in MoreInfo Section
  Base/settings.py
  Hairways/static/js/moreinfo.js
  Hairways/templates/moreinfo.html
Labels: feature :ok_hand:, ready for review

#123 Finishing booking process
  Hairways/static/css/cards.css
  Hairways/static/css/fixed_menu.css
  Hairways/static/css/footerstyle.css
  Hairways/static/css/index.css
  Hairways/static/css/jquery.datetimepicker.css
  Hairways/static/css/search.css
  Hairways/static/css/style.css
  Hairways/static/css/w3.css
  Hairways/static/js/javascript.js
  Hairways/static/js/scroll-horizontal.js
  Hairways/templates/base.html
  Hairways/templates/index.html
Labels: bug, ready for review

#124 styled sidebar and navbar to match theme
  Hairways/static/css/main.css
  Hairways/templates/base.html
  Hairways/templates/index.html
Labels: feature :ok_hand:, ready for review

#127 Tweaking carousel for smaller devices
  home/static/css/main.css
  home/templates/home/index.html
Labels: ready for review

#129 setting up travis ci
  .travis.yml
  home/tests.py
Labels: feature :ok_hand:
